title: Gil Moutinho
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Gil Moutinho, a professional Software Enginner. 
  In this space, I hope to introduce myself and tell a bit about my studies and professional life, 
  including my favorite projects I worked on.
baseurl: "gilmoutinho.github.io" # e.g. /blog
url: "" # e.g. http://example.com
bitbucket_username: 1130632
github_username:  GilMoutinho

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
